name: Unit Tests

on: [ pull_request, push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Build
        run: |
          dotnet restore
          dotnet build -c Release
      - name: Unit Tests
        run: dotnet test
